version: '3.1'

services:
  postgres:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${HUBGREP_CRAWLERS_POSTGRES_PASSWORD}

  service:
    build: .
    volumes:
      - ./:/var/task

    env_file: .env

    restart: ${RESTART}

    # uplink port to host
    ports:
      - 8080-8999:8080

    command: >
      bash -ic " \
        pip install -r requirements.txt
        flask run --host 0.0.0.0 --port 8080
        "
    tty: true

volumes:
  pgdata: